## Summary

Working memory and selective attention were historically regarded as distinct cognitive constructs reflecting the operation of distinct neural processes. Research has since established not only that there is a significant interaction between these two constructs, but that there appears to be considerable overlap in their function and operation. The experiments reported in this thesis have used EEG components to investigate the relationship between attention and working memory. Specifically, these experiments sought to clarify the attentional mechanisms involved in the short term storage of visual information in the face of increased load and distraction. 

In \textit{Study One} we carried out a systematic analysis of the effects of distractor presence on performance in a change detection task. The change detection task is an increasingly popular paradigm for studying working memory, especially for measuring individual working memory capacity. While some uses of the change detection paradigm have previously included irrelevant objects during encoding and retrieval stages, we lacked a detailed understanding of the effect of distraction on this task. First, we showed that even when distractor number is fixed for the entire block and distractor presence is perfectly predictable, distractors presented during encoding and retrieval lead to impaired performance on the task. This effect appears to scale, to some degree, with the number of distractors in the block. Signal detection measures reveal that this is a result of decreased sensitivity to change, rather than differences in participants' response bias. Our results also demonstrated that the block context has additional effects on behavioral performance. When distractor number changed on a trial-by-trial basis such that it always matched the number of targets, performance on the easiest trials is slightly worse, and performance on the most difficult trials is marginally better than equivalent trials from blocks where distractor number was fixed.

The second aspect of \textit{Study One} involved examining the effect of individual working memory capacity on the distractor effects described above. Greater working memory capacity is related to improved performance on the task in all contexts; however there was no relationship between filtering ability and capacity in blocks where distractor number is fixed. Working memory capacity nevertheless does appear to be predictive of an individual's ability to deal with the processing constraints that are unique to blocks where distractor number is varied and unpredictable on a trial-by-trial basis. These results suggest that the relationship between working memory capacity and distraction is more limited than previously indicated and appears to be specifically related to improved ability to adapt resources flexibly in an unpredictable context. In summary, \textit{Study One} detailed the circumstances in which distractors impair working memory performance, but also confirmed two robust effects in the change detection task: first, that increased working memory load negatively impacts working memory resources, and second, that distractor presence negatively impacts working memory resources. In the subsequent experiments, we sought to specify the attentional mechanisms related to these two effects using EEG indices of attentional control.

\textit{Studies Two} and \textit{Three} made use of a set of lateralized ERP components to provide dissociable measures of attentional mechanisms which are difficult to tease apart using conventional approaches. The first of these is the N2pc component, defined as an increased negative voltage at posterior electrodes contralateral to an attended stimulus. Accumulating evidence suggests that the N2pc indexes the shift of visual attention onto an attended object [@dellacqua_spatial_2006;@hickey_electrophysiological_2006;@luck_spatial_1994]. N2pc amplitude has also been used as a measure of attentional capture by relevant stimuli [@kiss_attentional_2008], or pop-out objects [@eimer_attentional_2007;@holguin_n2pc_2009]. The second identified lateralized ERP component is an enhanced positivity contralateral to distracting or irrelevant objects [@hickey_electrophysiological_2009;@hilimire_competitive_2009;@toffanin_p4pc:_2011], referred to as Ptc. Findings from research by @hilimire_target_2012 suggest that the component reflects distractor suppression during the disambiguation of target features. However, evidence that target objects can elicit Ptc suggests that it may more generally reflect attentional disengagement from an attended stimulus [@burra_distractor_2014;@hilimire_event-related_2014;@sawaki_common_2012]. The final lateralized component relevant to attentional control during visual search is the SPCN, a sustained lateralized negativity associated with short-term maintenance of task-relevant features [@jolicoeur_attentional_2006;@mazza_attentional_2007;@kiss_n2pc_2008;@jolicoeur_dissociation_2008]. By recording these components in the delay period of a change detection task, we hoped to elucidate which of these processes, if any, might be affected by working memory load and filtering.

In \textit{Study Two}, we used a dual-task paradigm to manipulate working memory load while participants carried out a visual search task. In the working memory portion of the task, participants encoded either one or two of the objects displayed on a screen, and then EEG was used to measure the N2pc, Ptc, and SPCN components elicited by the visual search displays but separately for targets and distractors. Our results showed that the lateralized response to distractors was affected by increased working memory load, and specifically the distractor Ptc appeared to be attenuated. This indicates that increased working memory load impacts on an individual's ability to disengage from irrelevant distractors in the visual search display. Taken together with previous research, the results of \textit{Study Two} bolster the suggestion that decreased working memory availability causes specific impairments to processes of distractor disengagement.

In \textit{Study Three}, we used a dual-task paradigm to follow up the effect of working memory distractors on behavioral performance. Participants again performed a dual working memory a visual search task where N2pc, Ptc, and SPCN could be measured separately for targets and distractors. Throughout the experiment, the participants would encode only one working memory item. Half of the time, this item was shown in the presence of an irrelevant working memory distractor, whereas the rest of the time it was shown by itself. The behavioral evidence showed that the presence of a working memory distractor results in behavioral impairments to the concurrent visual search that are similar to those observed under increased working memory load. Lateralized ERP components reveal that target processing is modulated by the presence of the working memory distractor while distractor processing appears unaffected. The fact that N2pc was larger in the condition where behavioral performance was impaired is somewhat counterintuitive; however, The link between N2pc amplitude and behavior is not straight forward and larger N2pc amplitude need not be assumed to index faster, or more accurate responses. Taken together, the results of \textit{Study Three} show that working memory distractors impact negatively on visual search performance and modulate target processing, but the effect appears to be complex and specifying the mechanism involved will rely on clarifying the function of the N2pc.

## Specifying the Relationship Between Attention and Working Memory

A consensus is building in favour of the general view that there is substantial functional overlap between working memory and selective attention. Previous research has attempted to specify the attentional processes that are related to working memory performance regarding both the within-subject effects of increased working memory load and the between-subject effects of working memory capacity. Optimal performance of selective attention relies on several underlying processes including target identification and selection, proactive suppression of possible distractors, and efficient disengagement from irrelevant distractors that capture attention [@carrasco_visual_2011]. Interference with any one of these processes would affect performance on an attention-based task. While previous work has consistently shown that low working memory availability impairs attention, it is still unclear which specific attentional processes it affects. Some evidence suggests that working memory availability engages processes involved in attending to targets [@scalf_working_2011], while other work has claimed that working memory is related to either distractor capture [@fukuda_human_2009], or distractor disengagement [@fukuda_individual_2011]. Our results support the view that within-subject manipulations of working memory load lead to impairments of distractor disengagement, however, in other respects the interaction is more complex.

One distinction that we have demonstrated is that the effect of working memory distractors on attentional control seems to be different to the effects of working memory load. In \textit{Study One} we documented the effects that irrelevant objects presented within a change detection task can have on working memory performance and the role that working memory capacity plays in addressing this distraction. A common explanation for this effect is that some individuals are worse at filtering out the irrelevant objects and therefore unnecessarily store them in working memory, reducing the availability of working memory resources [@vogel_neural_2005]. If this were the only mechanism operating, then we would expect that working memory distractor presence would have similar effects on attention as increased working memory load. However, the results of \textit{Study Two} and \textit{Three} are inconsistent with this view. While manipulations of working memory load in \textit{Study One} specifically interfere with the neural processing of distractors, manipulation of working memory distractor presence in \textit{Study Three} modulates the neural processing of targets. This implies that the presence of working memory distractors does not only impact on attention as a result of unnecessary encoding of the irrelevant stimulus, but that there are specific filtering processes engaged in the presence of working memory distractors which have a distinct effect on the subsequent operation of attention. However, when we performed posthoc comparisons to compare the component modulation in \textit{Study Two} to the component modulation \textit{Three}, while the distractor effect was significant, the target effect was only approaching significance. A detailed understanding of this mechanism will require further investigation, ideally using higher powered within-subjects designs that are explicitly designed to test this question. Little work has attempted to understand the effect of working memory distractors on attention it so far.

While the differences between these two studies raise some interesting questions about the relationship between attention and working memory, in some respects \textit{Study Three} also acts as a useful control for \textit{Study Two}. In \textit{Study Two}, participants encoded either one or two objects before performing the concurrent visual search task. To balance the amount of sensory information present in the displays, however, two objects were always presented on screen, and a preceding cue informed the participant whether they should encode one or both of these objects. As a result, the load conditions differed not only in the amount of information that should be encoded, but also in the amount of irrelevant information presented at encoding and retrieval. In the high load condition, all of the information on screen was task-relevant, whereas, in the low load condition, half of the information was relevant and half irrelevant. An alternate explanation for the results in \textit{Study Two} is that the modulation of distractor related processing is a result of this difference of irrelevant information rather than a difference of working memory load. In \textit{Study Three} however, working memory load was controlled throughout, with participants only ever encoding one object while the presence or absence of irrelevant information was manipulated. Consequently, if the presence of irrelevant information during working memory encoding and retrieval were responsible for the effects in \textit{Study Two} then we would expect the same effects to be present in \textit{Study Three}. The different results of \textit{Study Two} and \textit{Three} therefore support the assertion that the modulation of distractor disengagement processes in \textit{Study Two} was specifically related to changes in working memory load, and not working memory filtering.

The differences between \textit{Study Two} and \textit{Study Three} while informative for the reasons described above also present us with a potential problem. In \textit{Study Two}, the low load condition consisted of participants being shown two objects on a screen, while being expected to encode only one of those objects. In \textit{Study Three}, the distractor present condition also consisted of participants being shown two objects on screen and being expected to encode only one of those objects. Even though this condition is identical to the low load condition from \textit{Study Two}, in \textit{Study Three} we observed large, significant differences in response times between these two tasks suggesting that these two conditions, while identical at the single trial level, may not reflect two conditions where processing is identical for the subjects in each experiment. A possible explanation for this relates to the context effects we observed in \textit{Study One}.

In \textit{Study One}, our analyses showed that working memory accuracy and participants' sensitivity to changes in the change detection task were affected by the context of the block. The general effect appeared to show that in a variable distractor block where distractor number was unpredictable from trial to trial, performance on all trials became closer to the block average when compared to the exact same trial types taken from blocks where distractor number was fixed. This provides a plausible explanation for why identical trial types in \textit{Study Two} and \textit{Three} may result in different behavioral dynamics. It may be the case that in \textit{Study Two} when the average cognitive load across the experiment was higher, individuals processed the low load trials differently than in \textit{Study Three} when the cognitive load was lower. These results raise an important point with regard to the role that the eperimental context may play in investigations of the relationship between attention and working memory. It is possible that under low cognitive load, participants operate more or less at ceiling, and that small differences in target and distractor processing are only observeable when general cognitive load is high.

## Task-based differences in the effect of working memory on attention

While the results detailed in this thesis support provide evidence of the role that working memory availability plays in distractor disengagement, there remain a number of discrepant findings in the literature. In some cases, studies have failed to find evidence of any effect of working memory on selective attention, in others the effect has been found to be specific to target processing, whereas in other cases, such as ours, the effect has been linked exclusively to distractor processing. One significant factor which may help to explain these discrepancies is the nature of the task used to measure attention. It is plausible that working memory availability impacts on different attention processes depending on the details of the attention task that is used.

An example of this is shown by a range of studies which failed to find evidence for an interaction between working memory and selective attention. A basic observation in the attention literature is that when subjects are asked to search for a target amongst distractors, an increase in the number of distractors will require more items to be searched and therefore slower responses. If working memory impacts on visual search then adding a concurrent working memory load should result not only in a general slowing across all set sizes, but proportionally greater slowing of responses to large set sizes. Evidence has shown that the concurrent performance of working memory task slows responses to all set sizes, however, there is no additive effect of working memory load on set size [@logan1978attention;@woodman2001visual]. This evidence would appear to suggest that working memory has no interaction with attention processing at all. However, recent work has suggested that this may be a consequence of the fact that the search stimuli used in this task are usually highly homogeneous [@lavie_load_2004].

Evidence in favor of the role of working memory in visual search typically comes from paradigms involving salient distractors which compete with the target object for attention. For example in the anti-saccade task where participants must orient attention away from a salient onset cue, errors increase significantly under increased working memory load, and correlate negatively with working memory capacity [@kane2001controlled;@roberts1994prefrontal]. Similarly, when @lavie_role_2005 found evidence that increased working memory load interferes with visual search, their task included an irrelevant color singleton. The visual search task used in this thesis also supports this general observation. In our displays, a salient distractor was also presented concurrently with the salient target and its features overlapped with the target's features. Prior research, as well as the work presented in this thesis is therefore consistent with the suggestion that working memory availability impacts on attention processes in the context of competing pop-out distractors, and may otherwise be limited or absent.

Task specific differences may also explain the contention in the literature over whether working memory affects target or distractor processing. A common feature of tasks which have been used to support working memory's role in target processing is that target location is highly constrained throughout the experiment, and is never shared by irrelevant distractors [@scalf_working_2011;@heitz_focusing_2007;@poole_working-memory_2009;@ahmed_focusing_2012]. Typically these involve variations of the Eriksen flanker task where the target is always the central letter in a string of letters. If working memory resources are especially critical for maintaining target locations and contraining attention to those locations, then decreased availability in these tasks will result in specific failures of target selection. This may be less apparent in tasks where target location is unpredictable and therefore maintaining and constraining attention to a particular point in space is unrelated to search performance. 

While speculative, the suggestion that the effect of working memory may vary based on task in this way is consistent with the literature focussed on distractor processing. Typically, tasks which have demonstrated an effect of working memory availability on distractor processing have used unpredictable target locations that are shared by distractors. @fukuda_human_2009, for example, used a cued search task with eight locations where the target and distractor could appear at any of those locations from trial to trial. @mcnab_prefrontal_2008 used displays similar to those used in thesis, where a circular rings of objects was presented and targets and distractors could appear in any of the locations. @fukuda_individual_2011 had displays with four locations, which could again be occupied by either the target or a distractor on any given trial. In all cases these experiments presented evidence that working memory availability was specifically related to distractor processing, and unrelated to target processing. It is possible that working memory availability plays a critical role in processing distractors in a way which minimises their effect on search performance [@de_fockert_beyond_2013]. In that case, in visual search tasks where distractors are likely to be involuntarily attended to and processed, working memory's role in performance is primarily related to the process of distractor processing.

The role that task plays in our understanding of working memory and attention remains speculative. However, it is possible that discrepant findings with regard to the role of working memory processing on either target- or distractor-related processing may be an artefact of key differences in the attention tasks used. This raises a broader point with regard to the differential role that target enhancement and distractor suppression play in any given attention task. Search tasks where successful performance is more heavily dependent on a subject's ability to enhance target representations than to ignore distractors, will likely be more sensitive to detecting working memory's role in target processing. Conversely, tasks where most of the variance in performance is related to efficient distractor suppression will likely be more sensitive to detecting the role that working memkory plays in distractor processing. It may be crucial, therefore, for future research in this field to develop a precise understanding of the mechanisms invovled in performance of a given attention task, and to begin to compare the many influences that working memory may have on optimizing selective attention.

## Limitations

There are several limitations to the experimental designs used in this experiment. \textit{Study One} used a reasonably standard change detection paradigm and therefore suffers from the general limitations of that approach. Namely, that capacity estimates in the change detection paradigm assume that working memory consists of a set of discrete slots which each hold a single chunk of bound information [@rouder_how_2011]; however this claim is still contentious [@luck_visual_2013]. Change detection capacity estimates also depend on set size matching or exceeding individual capacity, which makes group averages problematic, and they do not account for participant error resulting from, for example, temporary lapses of attention [@rouder_how_2011]. In our case, however, part of the motivation for carrying out \textit{Study One} was to quantify the effect that irrelevant objects have on capacity estimates used in this specific task and therefore to alter the task to accommodate these issues would have undermined the generalizability of our results to the intended literature. A smaller issue which should be resolved in future iterations of this design would be to include zero distractor trials in the variable distractor block types. This would allow us to measure filtering cost for variable distractor blocks in the same way we did for fixed distractor blocks, and answer the question of whether block context alters this measure.

\textit{Studies Two} and \textit{Three} used a very similar paradigm which had its own set of limitations. For one, the working memory portion of the task used colored shapes as the objects to be stored and retrieved. It is possible that there is significant heterogeneity regarding the way in which participants store these kinds of objects, and that their different strategies affect the subsequent interference of visual search. The intention was for participants to store the objects as visual representations under the assumption that this would maximise the amount of interference imposed on the visual search task. It is possible however that some participants stored the names of the shapes and colors and therefore used a phonological storage mechanism. There are substantial theoretical, and empirical differences in the way that visual and verbal information are stored both in terms of the storage operations and anatomical networks involved [@crottaz-herbette_modality_2004;@baddeley_working_2003]. In our data, there is no way to know which strategy each participant used and therefore no way to quantify the effect that these strategy differences would have. However, this issue does not represent a critical problem given that we managed to demonstrate the desired behavioral interaction between attention and working memory. Future research could consider using more abstract visual objects (to limit phonological storage), or words (to restrict visual storage) to tease apart this effect and see whether or not it can be accounted for by one or both of these strategies.

There are also limitations to the visual search task used to measure the lateralized ERP components in \textit{Studies Two} and \textit{Three}. An inherent limitation of the use of the contralateral control method to separate target and distractor processing is that it involves presenting only one object on the horizontal midline while lateralizing the other. To maximise trial numbers that typically means that the target is on the midline half of the time, and the distractor is on the midline half of the time. While there are sixteen possible locations in the target-decoy task we used, only two of these are midline locations which means that targets do not randomly appear in any of the sixteen locations across the experiment; instead, they appear in two of the locations 50% of the time and in one of the other fourteen locations 50% of the time. It is possible that this significantly changes a participant's approach to the visual search task and that rather than searching the entire display, they focus their attention on the midline of the displays and only search elsewhere when the midline object is determined to be a target. This changes the dynamics of the visual search task, potentially improving average performance given that the target location is partially predictable. However, it is not clear that it changes the task in a way that undermines our conclusions. This could be solved by including trials where both objects are lateralized, although this would result in either a substantial increase in the total number of trials and therefore increased participant fatigue, or a reduction in the number of trials that can be used to isolate the ERP components of interest and consequently reduced signal-to-noise ratio. 

## Future Directions

The results of \textit{Study Three} raised a possible future direction for working memory research. One of the speculative explanations for our finding that N2pc was attenuated in the condition where behavior was improved is related to potential competition between working memory representations and the external world. To our knowledge, while there is ample evidence of competition between two externally presented stimuli, and a separate line of evidence for the representation of visual working memory in primary visual areas, there is no direct evidence looking at the implication that objects stored in working memory may, therefore, compete with external stimuli for representation in V1. To this end, we are currently collecting data for a study which investigates the possibility of this competition, and the effect that it could have on the lateralized components used in this thesis. Our task presents participants with a set of six visual search displays similar to those used in \textit{Studies Two} and \textit{Three}, where they are required to locate and store the target object on each display. By presenting these targets either within or across the horizontal midline, we can manipulate whether or not they are represented by neurons in the same hemisphere or across hemispheres. If these objects compete for representation in the same way as externally presented stimuli, then we would expect to see an attenuated N2pc to targets in the within hemisphere condition.

The conclusions of the studies presented in this thesis also indicate several broad lines of inquiry that future research should pursue. One such area would be a clarification of the cognitive processes indexed by each of the lateralized components. The conclusions in this thesis rely substantially on the use of the N2pc, Ptc, and SPCN elicited by targets and distractors to dissociate cognitive processes that are otherwise difficult to tease apart. At the outset of these studies we relied on prevailing views in the literature that N2pc reflects orienting of attention to potential targets, Ptc reflects subsequent suppression of a distractor which has captured attention, and SPCN reflects short-term storage of target features. While these are the most common conceptions of N2pc, Ptc, and SPCN, the functional role of each of these components is still contentious, and in some cases, our data better fit with alternate interpretations. This was best demonstrated in \textit{Study Three} where we concluded that working memory filtering impacts on early stages of target processing, however, we could not confidently explain the direction of the effects we observed. Using the prevailing view of N2pc as an index of attentional orienting, it was difficult to explain how working memory filtering led to impaired orienting but enhanced behavioral performance. An alternate account, that N2pc indexes the pre-attentive flagging of potential target locations potentially explains previous N2pc data, and also fits better with our results. Future research should focus on specifying the role of N2pc which would allow specification of the effect of working memory filtering in \textit{Study Three}.

There are similar contentions regarding the processes indexed by Ptc and SPCN, further limiting the conclusions we could draw from \textit{Studies Two} and \textit{Three}. Ptc, for example, was initially speculated to reflect a biasing signal which resolves competitive interactions between visual stimuli [@hilimire_competitive_2009;@hilimire_event-related_2010] but has since been suggested to reflect distractor suppression, and stimulus disengagement [@hilimire_dynamics_2011;@hilimire_event-related_2014;@hilimire_target_2012]. Similar questions surround the function of SPCN which has typically been associated with short-term storage as a result of its sensitivity to the number of stored objects. A recent study proposed instead that SPCN may reflect activation of working memory representations that are presently in the focus of attention. Given the demonstrated utility of these components in understanding the relationship between working memory and selective attention. Resolving these questions around the functions of N2pc, Ptc, and SPCN is critical for increasing the specificity of our understanding of this relationship.

Another area of research which may provide utility in understanding working memory and selective attention is steady-state evoked potentials (SSEP). The studies presented in this thesis rely on the use of lateralized components to provide dissociable measures of attentional processes that are otherwise difficult to measure. One of the main advantages of this approach is that targets and distractors are displayed simultaneously, but the processing of each stimulus can still be isolated. This allows us to measure the processing of a target in the presence of distraction while removing neural activity associated with distractors. Given the limitations of this technique that were mentioned above, an alternate possibility for isolating neural measures of targets and distractors in mixed displays is the SSEP technique. SSEPs are elicited when stimuli are flickered at a fixed frequency, causing entrainment of that frequency in recorded EEG activity. SSEPs are increasingly common as a method for studying attention and may be able to provide distinct measures of target and distractor processing that inform our understanding of attention's relationship with working memory. 

There is a reasonably large set of attention research based on SSEP designs because of their high signal-to-noise ratio and ability to distinguish neural processing of each stimulus in a multi-object display. An initial application of SSEPs to attention was performed by @morgan_selective_1996 when they showed participants two sets of stimuli, each on a box which flickered at a different frequency. When participants were required to attend to one of these sets of stimuli, neural activity at the flicker frequency was increased relative to the unattended frequency. This effect has been used to study the spatial distribution of attention by tagging locations with different frequencies [@muller_can_2002;@muller_sustained_2003;@malinowski_sustained_2007], as well as the dynamics of feature-based attention by tagging visual features with different frequencies [@malinowski_sustained_2007;@pei_neural_2002]. Importantly in our case, SSEPs have been used to show that attention both facilitates the processing of target colors while also actively inhibiting distractor colors. If SSEP designs can be used to measure distinct target selection and distractor suppression mechanisms then they may be able to provide similar utility as lateralized ERPs while avoiding the low signal-to-noise ratio and location-based constraints of our contralateral control design. 
`r #Why does WM filtering effect target processing? Understudied in general`

## General Conclusion

A detailed understanding of the relationship between working memory and selective attention is currently lacking in the psychology literature. Working memory capacity and working memory load are essential features of the working memory system which have been demonstrated to have some association with attentional control. The studies described in this thesis examine the interaction between working memory and attention using change detection paradigms and lateralized ERP components. They reveal that while working memory capacity is associated with neural indices of distractor capture, its relationship to distractibility is limited to contexts in which distractor number is unpredictable. Working memory load modulates neural responses to distractor processing but seems to be specifically related to distractor disengagement. Our results also showed that the inclusion of irrelevant objects during working memory encoding and retrieval has a significant impact on both working memory performance and performance on a concurrent visual search task. lateralized ERP components reveal that these irrelevant objects modulate processes of target selection. More broadly, this set of results demonstrates the utility of lateralized ERPs in providing dissociable measures of specific attentional subprocesses and therefore provides a promising tool for future research which investigates the relationship between working memory and selective attention.
